<?php

namespace SEO\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetaTagsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('seo_meta_tags')->insert([
            [
                'name' => 'description',
                'property' => '',
                'status' => 'active',
                'group' => '',
                'visibility' => 'page',
                'input_type' => 'textarea',
                'input_placeholder' => 'Meta Description',
                'input_label' => 'Meta Description',
                'input_info' => 'Meta Description',
            ],
            [
                'name' => 'keywords',
                'property' => '',
                'status' => 'inactive',
                'group' => '',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'Meta keywords',
                'input_label' => 'Meta keywords',
                'input_info' => 'Seperate your keywords by comma',
            ],
            [
                'name' => 'robots',
                'property' => '',
                'status' => 'active',
                'group' => '',
                'visibility' => 'global',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => '',
                'input_info' => '',
            ],
            [
                'name' => 'author',
                'property' => '',
                'status' => 'active',
                'group' => '',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => '',
                'input_info' => 'How to give credit to the person of company that made your website? You use the so called AUTHOR meta tag',
            ],
            [
                'name' => 'generator',
                'property' => '',
                'status' => 'inactive',
                'group' => '',
                'visibility' => 'global',
                'input_type' => 'text',
                'input_placeholder' => 'e.g. Laravel 5.4',
                'input_label' => 'Website building Program',
                'input_info' => 'How do you add a description of the program you used building your website ? You use the so called meta name generator tag',
            ],
            [
                'name' => '',
                'property' => 'og:locale',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'global',
                'input_type' => 'text',
                'input_placeholder' => 'e.g. en_US',
                'input_label' => 'Website Language',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'og:type',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'either article or webpage',
                'input_label' => 'Page Type',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'og:title',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'Page title',
                'input_label' => 'Page Title',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'og:description',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Meta description',
                'input_info' => 'When share to social media this will be shown along with our image.',
            ],
            [
                'name' => '',
                'property' => 'og:url',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Page Url',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'og:site_name',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Site Name',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'og:image',
                'status' => 'active',
                'group' => 'og',
                'visibility' => 'page',
                'input_type' => 'url',
                'input_placeholder' => '',
                'input_label' => 'Image',
                'input_info' => 'This image will be used on social media',
            ],
            [
                'name' => '',
                'property' => 'article:publisher',
                'status' => 'inactive',
                'group' => 'article',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Author of this page/post',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'article:section',
                'status' => 'inactive',
                'group' => 'article',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Category of this article',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'article:published_time',
                'status' => 'inactive',
                'group' => 'article',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Publication time',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'twitter:card',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'e.g. summary_large_image',
                'input_label' => 'Twitter Card',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'twitter:description',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Twitter description',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'twitter:title',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Twitter title',
                'input_info' => 'Same as page title',
            ],
            [
                'name' => '',
                'property' => 'twitter:site',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'e.g. @tuhin',
                'input_label' => 'Twitter username',
                'input_info' => '',
            ],
            [
                'name' => '',
                'property' => 'twitter:image',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => '',
                'input_label' => 'Twitter Image',
                'input_info' => 'This image will be shown when shared to twitter',
            ],
            [
                'name' => '',
                'property' => 'twitter:creator',
                'status' => 'inactive',
                'group' => 'twitter',
                'visibility' => 'page',
                'input_type' => 'text',
                'input_placeholder' => 'e.g. @tuhin',
                'input_label' => 'Twitter account holder',
                'input_info' => '',
            ]
        ]);
    }
}
